version: '3'

volumes:
  redis_data: {}
networks:
  webapp-net:
    driver: bridge

services:
  web:
    image: rv0lt/flaskrediswebapp
    ports:
      - "5000:5000"
    environment:
      REDIS_PWD: patata
      R_HOSTNAME: redis
    container_name: flask
    depends_on:
      - redis
    volumes:
      - .:/code
    networks:
      - webapp-net

  redis:
    image: redis:6.0.5
    expose:
      - 6379
    environment:
      REDIS_PWD: patata
    command: redis-server --requirepass $REDIS_PWD --appendonly yes
    networks:
      - webapp-net
    volumes:
      - redis_data:/data
    container_name: redis
